### ISSUE TITLE
Error creating group in the Start menu Setup.

### ISSUE THREAD

**Issue by VictorVG** [henrypp/errorlookup#1]
Error creating group in the Start menu Setup appears that the installer ignores the parent directory of the menu and as a result the group is created incorrectly. The error occurs in the following function NSIS (disassembled code):
```
SetOutPath $ COMMONSTARTMENU \ $ [44]
CreateShortCut "$ COMMONSTARTMENU \ $ [44] \ Error Lookup.lnk" "$ INSTDIR \ $ [45]" 0 0 0
CreateShortCut "$ COMMONSTARTMENU \ $ [44] \ License.lnk" "$ INSTDIR \ License.txt" 0 0 0
CreateShortCut "$ COMMONSTARTMENU \ $ [44] \ History.lnk" "$ INSTDIR \ History.txt" 0 0 0
CreateShortCut "$ COMMONSTARTMENU \ $ [44] \ Uninstall.lnk" "$ INSTDIR \ uninstall.exe" 0 0 0
```
which incorrectly identifies the parent group m as a result of a directory tree group is not created in the general start menu, and in the %USERPROFILE%\Main Menu. It is likely that this is a mistake earlier NSIS v3.0 because NSIS v2.46 ANSI I was not able to reproduce it to play. I usually use this code to avoid such phenomena:
```
!include "MUI.nsh"
...
Section -Icons
  SetShellVarContext all
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateDirectory "$SMPROGRAMS\$ICONS_GROUP"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\.....lnk
 ...
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd
```
which does not cause such errors.

**Comment by henrypp** [comment]
Thank you! I fix it and published nsis code, check it!

**Comment by VictorVG** [comment]
Thank you very much! The error is corrected, I checked it, so we can close this bug marked as "solved".
