### ISSUE TITLE
v2.3.2 - find wrong update for language pack, but SHA-256 for errorlookup.lng is equivalents for exist and download files

### ISSUE THREAD

**Issue by VictorVG** [henrypp/errorlookup#16]
v2.3.2 - find false update for language pack, but SHA-256 for errorlookup.lng is equivalents for exist  and download files:

SHA-256 for exist file:

33fba4f92b2a5a5a0d99f3f6d11510914f363fb101cfc331bc8ea330db030d6c *errorlookup.lng

SHA-256 for download file dated 29.10.2019:

33fba4f92b2a5a5a0d99f3f6d11510914f363fb101cfc331bc8ea330db030d6c *errorlookup.lng

detect and message `Update available (%s), download and install them?` is wrong and update is stop  then download 100% and not responded.
 
I download this version on https://www.henrypp.org/product/errorlookup web page.

**Comment by henrypp** [comment]
Hello,

this is [project sdk](https://github.com/henrypp/routine) bug, and it's [fixed](https://github.com/henrypp/routine/commit/54202c33c4817fa40a2f7a765f24daf7f8e389a5) after error lookup release. in near future, i hope to, build and release update error lookup binaries.

**Comment by VictorVG** [comment]
Thanks! I wait new source code.

**Comment by henrypp** [comment]
My misstake:
Bug, you described, are in project sdk and [already fixed](https://github.com/henrypp/routine/tree/579e01c29f8da4b9600796eeec55bcaeca68ce7d). Error Lookup codebase is not required to be change, just compile it.

**Comment by VictorVG** [comment]
Ok! I just clone Your git for compile (add new repo - Process Hacker, IntChecker, SumatrapDF, ... :)

**Comment by henrypp** [comment]
just vs2019, [pugixml](https://github.com/zeux/pugixml) & [routine](https://github.com/henrypp/routine) is required. close ticket when problem are solved.

**Comment by VictorVG** [comment]
Yes, I saw this after reading the assembly configs (I wanted to get around the challenge of 2010 - 2015, because at that moment they were available, but the note that the version 1.4.2 toolkit was required sent to chase teas until the compiler was free). Collected, it seems like the request will not be updated, only (maybe it's the technicians at the main provider again "setting up" something - they have a favorite pastime of doing something "setting up" so that at least take out the saints and then listen to angry users :)) as a result, a message is displayed about the unavailability of the update server.

But this is also displayed on your assembly, and therefore I thought that again these "kulibins" decided to "improve" something. Hands would tear them off for a crookedness. Colleagues once said to the great physicist Enirico Fermi, “Sir, when you enter the laboratory all the devices begin to explode, so it’s better to do theoretical physics, but we’ll deal with the devices ourselves!” :) And these should be said simply “To devices and servers don’t let in an intercontinental ballistic missile! Whoever admit will be fired without a severance pay and the opportunity to find work even as a junior assistant of a carrier of a broomstick to the smallest janitor in a garbage dump! "

**Comment by VictorVG** [comment]
I build use this [**Error Lookup Issues 16 try fix build SDK**](https://github.com/VictorVG/test/releases/tag/ELFix) - is working copy w/o output bin files. One message about update is display, but operation finished success. 

**P.S.**

True, I caught a kernel panic along the way, but it’s by the grace of Seagate Expansion+ 1TB- it seems that if the HDD doesn’t manage to clean out the debris, the road to return under warranty shines with zeros — its connection will erase the entire disk subsystem even on server controllers from HP with TI chips. And on a simple Ethron / NEC, the controller driver crashes, followed by a file system filter and a kernel panic - perfect hack, has not been seen for a long time. I will fuse the manufacturer and let them figure out where the firewood was broken.
