### ISSUE TITLE
Added Slovenian translation, per Date 11.01.2021

### ISSUE THREAD

**Issue by JadranR** [henrypp/errorlookup#19]
Hi,
Sloveniat translation for Error Lookup 2.4.1, pe Date 11.01.2021 added into Project.
Please, see attached screenshot too 👍 
With respect
Jadran Rudec
![Error Code](https://user-images.githubusercontent.com/53031490/104183097-b8690680-5411-11eb-9459-b162662b8521.jpg)

**Comment by henrypp** [comment]
errorlookup does not trimming input clipboard text, enter numbers manually

**Comment by JadranR** [comment]
Thanks :-)))
