### ISSUE TITLE
[Bug] Extraneous resource information causes DLL missing errors

### ISSUE THREAD

**Issue by Shuangcheng-Ni** [henrypp/errorlookup#29]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

2.5

### Windows version

Windows 11 (10.0.22621.3007)

### Steps to reproduce

1. Launch the application.

### Actual behavior

After launching the program, I get the following error messages:
```
Message:
{无法找到文件}
文件 %hs 不存在。

Status:
-1073741809 (0xC000000F)

Description:
ddputils.dll

Message:
{无法找到文件}
文件 %hs 不存在。

Status:
-1073741809 (0xC000000F)

Description:
cscsvc.dll

Message:
{无法找到文件}
文件 %hs 不存在。

Status:
-1073741809 (0xC000000F)

Description:
srm.dll
```
The program complains about some missing DLLs.

However, according to `dumpbin`, `errorlookup.exe` does not depend on these DLLs.
```
> dumpbin /dependents errorlookup.exe
Microsoft (R) COFF/PE Dumper Version 14.38.33130.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file errorlookup.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    KERNEL32.dll
    USER32.dll
    GDI32.dll
    SHELL32.dll
    ole32.dll
    ntdll.dll
    COMCTL32.dll
    dbghelp.dll
    SHLWAPI.dll
    api-ms-win-shcore-scaling-l1-1-1.dll
    UxTheme.dll
    VERSION.dll
    WINHTTP.dll
    XmlLite.dll

  Summary

        3000 .data
        3000 .pdata
       10000 .rdata
        1000 .reloc
        7000 .rsrc
       2A000 .text
        1000 _RDATA
```
These error messages can just be ignored and the program will still run correctly.

In fact, these errors are caused by extraneous resource information within the program. Therefore, a temporary workaround for users might be replacing these lines in the `.rsrc` section of `errorlookup.exe` with spaces.
```
<item file="ddputils.dll" text="Data Deduplication Library" />
<item file="cscsvc.dll" text="CSC Service API" />
<item file="srm.dll" text="File Server Resource Manager Common Library API" />
```
For developers, such resource information might be removed from the project configuration.

**Comment by henrypp** [comment]
now it is fixed, i release a new ver in a week (i think)
