### ISSUE TITLE
[Bug] Chinese GUI interface text exception

### ISSUE THREAD

**Issue by ProgrammerMAX114514** [henrypp/errorlookup#31]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

2.6

### Windows version

Windows 11 23H2

### Steps to reproduce

1. Start the program
2. Change the language to Chinese

### Actual behavior

![屏幕截图 2024-10-01 160033](https://github.com/user-attachments/assets/8cf19f42-44d5-4ee6-843a-44bff9139fe1)
![屏幕截图 2024-10-01 160628](https://github.com/user-attachments/assets/3acb1547-f6b0-42d5-9948-8bbd90d2e24b)
![屏幕截图 2024-10-01 160652](https://github.com/user-attachments/assets/1e963a8e-d29b-4890-95b6-2e285e420519)
![屏幕截图 2024-10-01 160657](https://github.com/user-attachments/assets/39e0bfc3-d043-4305-a112-bf5b9e5b3fed)
The Chinese text did not appear in the appropriate position, making the program's graphical interface a mess.
**Please note that some text is machine translated and may not be 100% accurate.**

**Comment by henrypp** [comment]
you may create pull request with change.

**Comment by ProgrammerMAX114514** [comment]
I'm sorry, but I don't have the ability to read and understand the program's codes, so it's dangerous to let me create a pull request. I'm just an ordinary junior high school student. What's more, it's difficult for me to connect to github, some texts like "Time out" and "Can't resolve host name" always appear on my screen when I'm using github.

**Comment by henrypp** [comment]
or you can just fix ini file and send updated file to my email/telegram
